# Generated by Django 4.1.7 on 2024-05-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('LA', 'Laundry'), ('CL', 'Cleaning'), ('AD', 'Administration')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.CharField(choices=[('LA', 'Laundry'), ('CL', 'Cleaning'), ('AD', 'Administration')], max_length=2),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('concept', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('turn_cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.turncash')),
            ],
        ),
    ]
