# Generated by Django 4.1.7 on 2024-07-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_employee_position_alter_shift_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='turncash',
            options={'verbose_name': 'Turno de Caja', 'verbose_name_plural': 'Turnos de Caja'},
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='concept',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='turn_cash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='rooms.turncash'),
        ),
    ]
