# Generated by Django 4.1.7 on 2024-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_cashmovement_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turncash',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
