# Generated by Django 4.1.7 on 2024-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_turncash_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turncash',
            name='turn_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
