# Generated by Django 4.1.3 on 2024-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_turncash_turn_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turncash',
            name='turn_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
