# Generated by Django 4.1.3 on 2024-08-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_departure_time_room_occupation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='vehicle_description',
            new_name='vehicle_info',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vehicle_plate',
        ),
        migrations.RemoveField(
            model_name='room',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupation_time',
        ),
        migrations.AddField(
            model_name='room',
            name='rent_duration',
            field=models.IntegerField(default=4),
        ),
    ]
