# Generated by Django 4.1.3 on 2024-08-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_rename_vehicle_description_payment_vehicle_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rent_duration',
        ),
        migrations.AddField(
            model_name='payment',
            name='rent_duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='occupation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
