# Generated by Django 4.1.3 on 2024-08-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_remove_room_rent_duration_payment_rent_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
    ]
