# Generated by Django 4.1.3 on 2024-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_remove_payment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
