# Generated by Django 4.1.3 on 2024-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_room_cleaning_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
