# Generated by Django 4.1.3 on 2024-08-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RoomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('OC', 'Occupied'), ('CL', 'Cleaning'), ('MT', 'Maintenance'), ('AV', 'Available'), ('LI', 'Clean')], max_length=2)),
                ('new_status', models.CharField(choices=[('OC', 'Occupied'), ('CL', 'Cleaning'), ('MT', 'Maintenance'), ('AV', 'Available'), ('LI', 'Clean')], max_length=2)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
